version: "3"

services:
        db:
                image: postgres:12.2
                volumes:
                        - /db
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_PASSWORD=
                        POSTGRES_USER=
                restart: always

        backend:
                image: wwxs_backend:latest
                build: .
                ports:
                        - "8080:8080"
                environment:
                        VAR=
                restart: always

